volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: praeitor/kittygram_backend
    container_name: backend
    env_file: .env
    restart: always
    depends_on:
      - postgres
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: praeitor/kittygram_frontend
    container_name: frontend
    env_file: .env
    restart: always
    ports:
      - "8000:8000"
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: praeitor/kittygram_gateway
    container_name: gateway
    env_file: .env
    restart: always
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - static:/staticfiles
      - media:/app/media
