---

name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the Terraform action'
        required: true
        default: 'plan'
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
      TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
      TF_VAR_yc_user: ${{ secrets.YC_USER }}
      TF_VAR_yc_ssh_public_key: ${{ secrets.YC_SSH_PUBLIC_KEY }}
      TF_VAR_yc_zone: "ru-central1-a"

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure YC authentication
        run: echo '${{ secrets.YC_KEY_JSON }}' > service_account_key_file.json

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="access_key=$ACCESS_KEY" \
            -backend-config="secret_key=$SECRET_KEY"
        env:
          ACCESS_KEY: ${{ secrets.YC_ACCESS_KEY_ID }}
          SECRET_KEY: ${{ secrets.YC_SECRET }}

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan
